Realm.create({"id"=>"afrotropics", "title"=>"Afrotropics"})
Subrealm.create({"id"=>"southern-afrotropics", "title"=>"Southern Afrotropics", "realm_id"=>"afrotropics"})
Subrealm.create({"id"=>"equatorial-afrotropics", "title"=>"Equatorial Afrotropics", "realm_id"=>"afrotropics"})
Subrealm.create({"id"=>"sub-equatorial-afrotropics", "title"=>"Sub-equatorial Afrotropics", "realm_id"=>"afrotropics"})
Subrealm.create({"id"=>"madagascar-and-east-african-coast", "title"=>"Madagascar and East African Coast", "realm_id"=>"afrotropics"})
Subrealm.create({"id"=>"sub-saharan-afrotropics", "title"=>"Sub-saharan Afrotropics", "realm_id"=>"afrotropics"})

Realm.create({"id"=>"antarctica", "title"=>"Antarctica"})
Subrealm.create({"id"=>"antarctic-continent-and-islands", "title"=>"Antarctic Continent and Islands", "realm_id"=>"antarctica"})

Realm.create({"id"=>"australasia", "title"=>"Australasia"})
Subrealm.create({"id"=>"new-zealand", "title"=>"New Zealand", "realm_id"=>"australasia"})
Subrealm.create({"id"=>"australasian-islands-and-eastern-indonesia", "title"=>"Australasian Islands and Eastern Indonesia", "realm_id"=>"australasia"})
Subrealm.create({"id"=>"australia", "title"=>"Australia", "realm_id"=>"australasia"})

Realm.create({"id"=>"central-america", "title"=>"Central America"})
Subrealm.create({"id"=>"central-america", "title"=>"Central America", "realm_id"=>"central-america"})
Subrealm.create({"id"=>"caribbean", "title"=>"Caribbean", "realm_id"=>"central-america"})

Realm.create({"id"=>"central-eurasia", "title"=>"Central Eurasia"})
Subrealm.create({"id"=>"persian-deserts-and-forests", "title"=>"Persian Deserts and Forests", "realm_id"=>"central-eurasia"})
Subrealm.create({"id"=>"tien-shan-mountains", "title"=>"Tien Shan Mountains", "realm_id"=>"central-eurasia"})
Subrealm.create({"id"=>"caspian-sea-and-central-asian-deserts", "title"=>"Caspian Sea and Central Asian Deserts", "realm_id"=>"central-eurasia"})
Subrealm.create({"id"=>"kazakh-steppes-and-hemiboreal-forests", "title"=>"Kazakh Steppes and Hemiboreal Forests", "realm_id"=>"central-eurasia"})

Realm.create({"id"=>"eastern-eurasia", "title"=>"Eastern Eurasia"})
Subrealm.create({"id"=>"east-asian-deserts", "title"=>"East Asian Deserts", "realm_id"=>"eastern-eurasia"})
Subrealm.create({"id"=>"himalayas-and-tibetan-plateau", "title"=>"Himalayas and Tibetan Plateau", "realm_id"=>"eastern-eurasia"})
Subrealm.create({"id"=>"mongolian-grasslands", "title"=>"Mongolian Grasslands", "realm_id"=>"eastern-eurasia"})
Subrealm.create({"id"=>"northeast-asian-forests", "title"=>"Northeast Asian Forests", "realm_id"=>"eastern-eurasia"})
Subrealm.create({"id"=>"japanese-islands", "title"=>"Japanese Islands", "realm_id"=>"eastern-eurasia"})
Subrealm.create({"id"=>"central-east-asian-forests", "title"=>"Central East Asian Forests", "realm_id"=>"eastern-eurasia"})
Subrealm.create({"id"=>"altai-sayan-mountains", "title"=>"Altai-Sayan Mountains", "realm_id"=>"eastern-eurasia"})

Realm.create({"id"=>"indomalaya", "title"=>"Indomalaya"})
Subrealm.create({"id"=>"malaysia-and-western-indonesia", "title"=>"Malaysia and Western Indonesia", "realm_id"=>"indomalaya"})
Subrealm.create({"id"=>"indian-subcontinent", "title"=>"Indian Subcontinent", "realm_id"=>"indomalaya"})
Subrealm.create({"id"=>"southeast-asian-forests", "title"=>"Southeast Asian Forests", "realm_id"=>"indomalaya"})

Realm.create({"id"=>"northern-america", "title"=>"Northern America"})
Subrealm.create({"id"=>"great-plains", "title"=>"Great Plains", "realm_id"=>"northern-america"})
Subrealm.create({"id"=>"american-west", "title"=>"American West", "realm_id"=>"northern-america"})
Subrealm.create({"id"=>"north-pacific-coast", "title"=>"North Pacific Coast", "realm_id"=>"northern-america"})
Subrealm.create({"id"=>"northeast-american-forests", "title"=>"Northeast American Forests", "realm_id"=>"northern-america"})
Subrealm.create({"id"=>"southeast-us-savannas-and-forests", "title"=>"Southeast U.S. Savannas and Forests", "realm_id"=>"northern-america"})
Subrealm.create({"id"=>"mexican-drylands", "title"=>"Mexican Drylands", "realm_id"=>"northern-america"})

Realm.create({"id"=>"oceania", "title"=>"Oceania"})
Subrealm.create({"id"=>"oceanic-islands", "title"=>"Oceanic Islands", "realm_id"=>"oceania"})

Realm.create({"id"=>"southern-america", "title"=>"Southern America"})
Subrealm.create({"id"=>"andes-and-pacific-coast", "title"=>"Andes and Pacific Coast", "realm_id"=>"southern-america"})
Subrealm.create({"id"=>"south-american-grasslands", "title"=>"South American Grasslands", "realm_id"=>"southern-america"})
Subrealm.create({"id"=>"brazil-cerrado-and-atlantic-coast", "title"=>"Brazil Cerrado and Atlantic Coast", "realm_id"=>"southern-america"})
Subrealm.create({"id"=>"amazonia", "title"=>"Amazonia", "realm_id"=>"southern-america"})
Subrealm.create({"id"=>"upper-south-america", "title"=>"Upper South America", "realm_id"=>"southern-america"})

Realm.create({"id"=>"southern-eurasia", "title"=>"Southern Eurasia"})
Subrealm.create({"id"=>"north-africa", "title"=>"North Africa", "realm_id"=>"southern-eurasia"})
Subrealm.create({"id"=>"greater-arabian-peninsula", "title"=>"Greater Arabian Peninsula", "realm_id"=>"southern-eurasia"})

Realm.create({"id"=>"subarctic-america", "title"=>"Subarctic America"})
Subrealm.create({"id"=>"alaska", "title"=>"Alaska", "realm_id"=>"subarctic-america"})
Subrealm.create({"id"=>"canadian-tundra", "title"=>"Canadian Tundra", "realm_id"=>"subarctic-america"})
Subrealm.create({"id"=>"canadian-boreal-forests", "title"=>"Canadian Boreal Forests", "realm_id"=>"subarctic-america"})
Subrealm.create({"id"=>"greenland", "title"=>"Greenland", "realm_id"=>"subarctic-america"})

Realm.create({"id"=>"subarctic-eurasia", "title"=>"Subarctic Eurasia"})
Subrealm.create({"id"=>"scandinavia-and-west-boreal-forests", "title"=>"Scandinavia & West Boreal Forests", "realm_id"=>"subarctic-eurasia"})
Subrealm.create({"id"=>"palearctic-tundra", "title"=>"Palearctic Tundra", "realm_id"=>"subarctic-eurasia"})
Subrealm.create({"id"=>"sea-of-okhotsk-and-bearing-tundra-taiga", "title"=>"Sea of Okhotsk and Bearing Tundra/Taiga", "realm_id"=>"subarctic-eurasia"})
Subrealm.create({"id"=>"siberia-and-east-boreal-forests", "title"=>"Siberia and East Boreal Forests", "realm_id"=>"subarctic-eurasia"})

Realm.create({"id"=>"western-eurasia", "title"=>"Western Eurasia"})
Subrealm.create({"id"=>"britain", "title"=>"Britain", "realm_id"=>"western-eurasia"})
Subrealm.create({"id"=>"greater-european-forests", "title"=>"Greater European Forests", "realm_id"=>"western-eurasia"})
Subrealm.create({"id"=>"european-mountain-forests", "title"=>"European Mountain Forests", "realm_id"=>"western-eurasia"})
Subrealm.create({"id"=>"black-sea-forests-and-steppe", "title"=>"Black Sea Forests and Steppe", "realm_id"=>"western-eurasia"})
Subrealm.create({"id"=>"mediterranean", "title"=>"Mediterranean", "realm_id"=>"western-eurasia"})
